public class REG_OUT {
    short register_out(short ASCII_reg){
        short c;
        switch (ASCII_reg){
            case 0x00: c = 0x63;
            break;
            case 0x01: c = 0x7c;
            break;
            case 0x02: c = 0x77;
            break;
            case 0x03: c = 0x7b;
            break;
            case 0x04: c = 0xf2;
            break;
            case 0x05: c = 0x6b;
            break;
            case 0x06: c = 0x6f;
            break;
            case 0x07: c = 0xc5;
            break;
            case 0x08: c = 0x30;
            break;
            case 0x09: c = 0x01;
            break;
            case 0x0a: c = 0x67;
            break;
            case 0x0b: c = 0x2b;
            break;
            case 0x0c: c = 0xfe;
            break;
            case 0x0d: c = 0xd7;
            break;
            case 0x0e: c = 0xab;
            break;
            case 0x0f: c = 0x76;
            break;
            case 0x10: c = 0xca;
            break;
            case 0x11: c = 0x82;
            break;
            case 0x12: c = 0xc9;
            break;
            case 0x13: c = 0x7d;
            break;
            case 0x14: c = 0xfa;
            break;
            case 0x15: c = 0x59;
            break;
            case 0x16: c = 0x47;
            break;
            case 0x17: c = 0xf0;
            break;
            case 0x18: c = 0xad;
            break;
            case 0x19: c = 0xd4;
            break;
            case 0x1a: c = 0xa2;
            break;
            case 0x1b: c = 0xaf;
            break;
            case 0x1c: c = 0x9c;
            break;
            case 0x1d: c = 0xa4;
            break;
            case 0x1e: c = 0x72;
            break;
            case 0x1f: c = 0xc0;
            break;
            case 0x20: c = 0xb7;
            break;
            case 0x21: c = 0xfd;
            break;
            case 0x22: c = 0x93;
            break;
            case 0x23: c = 0x26;
            break;
            case 0x24: c = 0x36;
            break;
            case 0x25: c = 0x3f;
            break;
            case 0x26: c = 0xf7;
            break;
            case 0x27: c = 0xcc;
            break;
            case 0x28: c = 0x34;
            break;
            case 0x29: c = 0xa5;
            break;
            case 0x2a: c = 0xe5;
            break;
            case 0x2b: c = 0xf1;
            break;
            case 0x2c: c = 0x71;
            break;
            case 0x2d: c = 0xd8;
            break;
            case 0x2e: c = 0x31;
            break;
            case 0x2f: c = 0x15;
            break;
            case 0x30: c = 0x04;
            break;
            case 0x31: c = 0xc7;
            break;
            case 0x32: c = 0x23;
            break;
            case 0x33: c = 0xc3;
            break;
            case 0x34: c = 0x18;
            break;
            case 0x35: c = 0x96;
            break;
            case 0x36: c = 0x05;
            break;
            case 0x37: c = 0x9a;
            break;
            case 0x38: c = 0x07;
            break;
            case 0x39: c = 0x12;
            break;
            case 0x3a: c = 0x80;
            break;
            case 0x3b: c = 0xe2;
            break;
            case 0x3c: c = 0xeb;
            break;
            case 0x3d: c = 0x27;
            break;
            case 0x3e: c = 0xb2;
            break;
            case 0x3f: c = 0x75;
            break;
            case 0x40: c = 0x09;
            break;
            case 0x41: c = 0x83;
            break;
            case 0x42: c = 0x2c;
            break;
            case 0x43: c = 0x1a;
            break;
            case 0x44: c = 0x1b;
            break;
            case 0x45: c = 0x6e;
            break;
            case 0x46: c = 0x5a;
            break;
            case 0x47: c = 0xa0;
            break;
            case 0x48: c = 0x52;
            break;
            case 0x49: c = 0x3b;
            break;
            case 0x4a: c = 0xd6;
            break;
            case 0x4b: c = 0xb3;
            break;
            case 0x4c: c = 0x29;
            break;
            case 0x4d: c = 0xe3;
            break;
            case 0x4e: c = 0x2f;
            break;
            case 0x4f: c = 0x84;
            break;
            case 0x50: c = 0x53;
            break;
            case 0x51: c = 0xd1;
            break;
            case 0x52: c = 0x00;
            break;
            case 0x53: c = 0xed;
            break;
            case 0x54: c = 0x20;
            break;
            case 0x55: c = 0xfc;
            break;
            case 0x56: c = 0xb1;
            break;
            case 0x57: c = 0x5b;
            break;
            case 0x58: c = 0x6a;
            break;
            case 0x59: c = 0xcb;
            break;
            case 0x5a: c = 0xbe;
            break;
            case 0x5b: c = 0x39;
            break;
            case 0x5c: c = 0x4a;
            break;
            case 0x5d: c = 0x4c;
            break;
            case 0x5e: c = 0x58;
            break;
            case 0x5f: c = 0xcf;
            break;
            case 0x60: c = 0xd0;
            break;
            case 0x61: c = 0xef;
            break;
            case 0x62: c = 0xaa;
            break;
            case 0x63: c = 0xfb;
            break;
            case 0x64: c = 0x43;
            break;
            case 0x65: c = 0x4d;
            break;
            case 0x66: c = 0x33;
            break;
            case 0x67: c = 0x85;
            break;
            case 0x68: c = 0x45;
            break;
            case 0x69: c = 0xf9;
            break;
            case 0x6a: c = 0x02;
            break;
            case 0x6b: c = 0x7f;
            break;
            case 0x6c: c = 0x50;
            break;
            case 0x6d: c = 0x3c;
            break;
            case 0x6e: c = 0x9f;
            break;
            case 0x6f: c = 0xa8;
            break;
            case 0x70: c = 0x51;
            break;
            case 0x71: c = 0xa3;
            break;
            case 0x72: c = 0x40;
            break;
            case 0x73: c = 0x8f;
            break;
            case 0x74: c = 0x92;
            break;
            case 0x75: c = 0x9d;
            break;
            case 0x76: c = 0x38;
            break;
            case 0x77: c = 0xf5;
            break;
            case 0x78: c = 0xbc;
            break;
            case 0x79: c = 0xb6;
            break;
            case 0x7a: c = 0xda;
            break;
            case 0x7b: c = 0x21;
            break;
            case 0x7c: c = 0x10;
            break;
            case 0x7d: c = 0xff;
            break;
            case 0x7e: c = 0xf3;
            break;
            case 0x7f: c = 0xd2;
            break;
            case 0x80: c = 0xcd;
            break;
            case 0x81: c = 0x0c;
            break;
            case 0x82: c = 0x13;
            break;
            case 0x83: c = 0xec;
            break;
            case 0x84: c = 0x5f;
            break;
            case 0x85: c = 0x97;
            break;
            case 0x86: c = 0x44;
            break;
            case 0x87: c = 0x17;
            break;
            case 0x88: c = 0xc4;
            break;
            case 0x89: c = 0xa7;
            break;
            case 0x8a: c = 0x7e;
            break;
            case 0x8b: c = 0x3d;
            break;
            case 0x8c: c = 0x64;
            break;
            case 0x8d: c = 0x5d;
            break;
            case 0x8e: c = 0x19;
            break;
            case 0x8f: c = 0x73;
            break;
            case 0x90: c = 0x60;
            break;
            case 0x91: c = 0x81;
            break;
            case 0x92: c = 0x4f;
            break;
            case 0x93: c = 0xdc;
            break;
            case 0x94: c = 0x22;
            break;
            case 0x95: c = 0x2a;
            break;
            case 0x96: c = 0x90;
            break;
            case 0x97: c = 0x88;
            break;
            case 0x98: c = 0x46;
            break;
            case 0x99: c = 0xee;
            break;
            case 0x9a: c = 0xb8;
            break;
            case 0x9b: c = 0x14;
            break;
            case 0x9c: c = 0xde;
            break;
            case 0x9d: c = 0x5e;
            break;
            case 0x9e: c = 0x0b;
            break;
            case 0x9f: c = 0xdb;
            break;
            case 0xa0: c = 0xe0;
            break;
            case 0xa1: c = 0x32;
            break;
            case 0xa2: c = 0x3a;
            break;
            case 0xa3: c = 0x0a;
            break;
            case 0xa4: c = 0x49;
            break;
            case 0xa5: c = 0x06;
            break;
            case 0xa6: c = 0x24;
            break;
            case 0xa7: c = 0x5c;
            break;
            case 0xa8: c = 0xc2;
            break;
            case 0xa9: c = 0xd3;
            break;
            case 0xaa: c = 0xac;
            break;
            case 0xab: c = 0x62;
            break;
            case 0xac: c = 0x91;
            break;
            case 0xad: c = 0x95;
            break;
            case 0xae: c = 0xe4;
            break;
            case 0xaf: c = 0x79;
            break;
            case 0xb0: c = 0xe7;
            break;
            case 0xb1: c = 0xc8;
            break;
            case 0xb2: c = 0x37;
            break;
            case 0xb3: c = 0x6d;
            break;
            case 0xb4: c = 0x8d;
            break;
            case 0xb5: c = 0xd5;
            break;
            case 0xb6: c = 0x4e;
            break;
            case 0xb7: c = 0xa9;
            break;
            case 0xb8: c = 0x6c;
            break;
            case 0xb9: c = 0x56;
            break;
            case 0xba: c = 0xf4;
            break;
            case 0xbb: c = 0xea;
            break;
            case 0xbc: c = 0x65;
            break;
            case 0xbd: c = 0x7a;
            break;
            case 0xbe: c = 0xae;
            break;
            case 0xbf: c = 0x08;
            break;
            case 0xc0: c = 0xba;
            break;
            case 0xc1: c = 0x78;
            break;
            case 0xc2: c = 0x25;
            break;
            case 0xc3: c = 0x2e;
            break;
            case 0xc4: c = 0x1c;
            break;
            case 0xc5: c = 0xa6;
            break;
            case 0xc6: c = 0xb4;
            break;
            case 0xc7: c = 0xc6;
            break;
            case 0xc8: c = 0xe8;
            break;
            case 0xc9: c = 0xdd;
            break;
            case 0xca: c = 0x74;
            break;
            case 0xcb: c = 0x1f;
            break;
            case 0xcc: c = 0x4b;
            break;
            case 0xcd: c = 0xbd;
            break;
            case 0xce: c = 0x8b;
            break;
            case 0xcf: c = 0x8a;
            break;
            case 0xd0: c = 0x70;
            break;
            case 0xd1: c = 0x3e;
            break;
            case 0xd2: c = 0xb5;
            break;
            case 0xd3: c = 0x66;
            break;
            case 0xd4: c = 0x48;
            break;
            case 0xd5: c = 0x03;
            break;
            case 0xd6: c = 0xf6;
            break;
            case 0xd7: c = 0x0e;
            break;
            case 0xd8: c = 0x61;
            break;
            case 0xd9: c = 0x35;
            break;
            case 0xda: c = 0x57;
            break;
            case 0xdb: c = 0xb9;
            break;
            case 0xdc: c = 0x86;
            break;
            case 0xdd: c = 0xc1;
            break;
            case 0xde: c = 0x1d;
            break;
            case 0xdf: c = 0x9e;
            break;
            case 0xe0: c = 0xe1;
            break;
            case 0xe1: c = 0xf8;
            break;
            case 0xe2: c = 0x98;
            break;
            case 0xe3: c = 0x11;
            break;
            case 0xe4: c = 0x69;
            break;
            case 0xe5: c = 0xd9;
            break;
            case 0xe6: c = 0x8e;
            break;
            case 0xe7: c = 0x94;
            break;
            case 0xe8: c = 0x9b;
            break;
            case 0xe9: c = 0x1e;
            break;
            case 0xea: c = 0x87;
            break;
            case 0xeb: c = 0xe9;
            break;
            case 0xec: c = 0xce;
            break;
            case 0xed: c = 0x55;
            break;
            case 0xee: c = 0x28;
            break;
            case 0xef: c = 0xdf;
            break;
            case 0xf0: c = 0x8c;
            break;
            case 0xf1: c = 0xa1;
            break;
            case 0xf2: c = 0x89;
            break;
            case 0xf3: c = 0x0d;
            break;
            case 0xf4: c = 0xbf;
            break;
            case 0xf5: c = 0xe6;
            break;
            case 0xf6: c = 0x42;
            break;
            case 0xf7: c = 0x68;
            break;
            case 0xf8: c = 0x41;
            break;
            case 0xf9: c = 0x99;
            break;
            case 0xfa: c = 0x2d;
            break;
            case 0xfb: c = 0x0f;
            break;
            case 0xfc: c = 0xb0;
            break;
            case 0xfd: c = 0x54;
            break;
            case 0xfe: c = 0xbb;
            break;
            case 0xff: c = 0x16;
            break;
            default: c=0x00;
        }
        return c;
    }
}
